### ISSUE TITLE
Question about sampling dataset

### ISSUE THREAD

**Issue by LucyLu-LX** [zhichunguo/Meta-MGNN#2]
Hi @zhichunguo 

I am confused about the meaning of [obtain_distr_list](https://github.com/zhichunguo/Meta-MGNN/blob/b76c04057ebbf19e164cb101e8a9b9b758f9f008/samples.py#L4). Does it stand for [training, testing] or [query, support] ? 

Besides, what's `support_list += random.sample(range(distri_list[task][0],len(data)), m_support)` for in 
https://github.com/zhichunguo/Meta-MGNN/blob/b76c04057ebbf19e164cb101e8a9b9b758f9f008/samples.py#L17
and 
https://github.com/zhichunguo/Meta-MGNN/blob/b76c04057ebbf19e164cb101e8a9b9b758f9f008/samples.py#L32

which doubles the support set.

what I think is that **obtain_distr_list** pre-define the set of query and support in each task and will not change in the entire training process. For each training loop, query dataset and support dataset should be sampled from these two sets based on the defined query and support number.  Please let me know if I was wrong.

**Comment by zhichunguo** [comment]
Hi, 

Thanks for your interest in our work!  `obtain_distr_list` is utilized to calculate the number of positive data and negative data for each task in the specific dataset. In the training process, we will sample m_support positive examples and negative examples for each task as the support part for each training loop.

**Comment by LucyLu-LX** [comment]
That makes sense!
Thanks for your explanation.

**Comment by shrimonmuke0202** [comment]
Hi 
How did not get the positive and negative data for each task in the specific dataset?

**Comment by zhichunguo** [comment]
For each dataset, there are positive (1) and negative (0) labels for each task (property).

**Comment by shrimonmuke0202** [comment]
Thank you for your email
Is this problem can be formulate as graph regression problem. As I have
task which is a regression problem. How can I apply few shot for regression
task.
