### ISSUE TITLE
Tasks distribution: how did you divide the data?

### ISSUE THREAD

**Issue by qm-intel** [zhichunguo/Meta-MGNN#3]
Hi, thanks for your great contribution. 

I am trying to understand you code. Can you please explain what is the reason you have set these numbers in [this line ](https://github.com/zhichunguo/Meta-MGNN/blob/b76c04057ebbf19e164cb101e8a9b9b758f9f008/samples.py#L8) for `tox21` dataset?

and how did you split the datasets? For example, in `splitdata.py`, in [line 27](https://github.com/zhichunguo/Meta-MGNN/blob/b76c04057ebbf19e164cb101e8a9b9b758f9f008/Original_datasets/splitdata.py#L27), you have set a number for for loop as `618`. can you explain on this? 

The other question is that, does any smiles sequence repeated in different tasks?
For example:

`0,,0,,1,,,1,0,1,0,1,TOX25232,O=C(O)Cc1cc(I)c(Oc2ccc(O)c(I)c2)c(I)c1`

Is this sequence included as a sample for 4 tasks `SR-HSE`,`SR-p53`, `NR-ER`, and `SR-ARE`?

Thank you

**Comment by zhichunguo** [comment]
Hi,

Thanks for your interest in our work.

We split the datasets according to different properties. 618 is the number of different predicted molecular properties for that dataset. The numbers in that line for the tox21 dataset are the number of positive and negative examples for each molecular property. 

Yes, the smiles sequence could be repeated in different tasks. But they are used to predict different properties in different tasks.

Please feel free to contact us with any further concerns or questions.

Best regards,
Zhichun

**Comment by qm-intel** [comment]
Thanks for your prompt response. 

>We split the datasets according to different properties. 618 is the number of different predicted molecular properties for that dataset. 

For example for `tox21`, we have 12 property prediction. this 618 should be changed to 12? or somthing else?

and for task `SR-p53` , there are [6351,423] (negative ,positive) values.

**Comment by zhichunguo** [comment]
> For example for tox21, we have 12 property prediction. this 618 should be changed to 12? or somthing else?

Yes. 

> and for task SR-p53 , there are [6351,423] (negative ,positive) values.

Yes, you need to change that list according to the number of positive and negative examples for each property based on your target dataset.

**Comment by qm-intel** [comment]
@zhichunguo Thanks a lot for your help and clarification
