### ISSUE TITLE
Where meta_lr is being used?

### ISSUE THREAD

**Issue by qm-intel** [zhichunguo/Meta-MGNN#4]
@zhichunguo

Hi, I am reviewing your code and realized that your are not using [self.meta_lr](https://github.com/zhichunguo/Meta-MGNN/blob/e72ee6508f24b8eb2e528153c50b44d6e717a53c/meta_model.py#L71)  in the `meta_model.py`. Can you please explain where this meta_lr is used in your code? 

Thanks

**Comment by zhichunguo** [comment]
Hi, 

Please check meta_lr, which is utilized [here](https://github.com/zhichunguo/Meta-MGNN/blob/e72ee6508f24b8eb2e528153c50b44d6e717a53c/meta_model.py#L111).

Thanks,
Zhichun

**Comment by qm-intel** [comment]
@zhichunguo  Sorry I missed that line, thanks again for your help.
